"""
================================================================
  KAY´S SNAKE QUEST  —  NEON ARCADE EDITION
  A single-file pygame-ce game. Spanglish UI. CRT vibes.
================================================================

HOW TO RUN
----------
Local (Windows / VS Code):
    pip install pygame-ce
    python main.py

In the browser with pygbag:
    pip install pygbag
    pygbag main.py
    # then open http://localhost:8000

CONTROLS
--------
    SPACE        Start / Restart
    Arrows/WASD  Mover la culebrita
    P            Pause
    ESC          Back to menu / Quit from menu

NO external assets required. All art is generated by code.
Optional music file (loaded only if it exists):
    assets/music/theme.wav
"""

import asyncio
import math
import os
import random
import pygame


# ==========================================================================
# 🎨   CONFIGURACIÓN  /  CONFIGURATION
# Cambia estos valores para personalizar el juego.
# Change these values to customize the game.
# ==========================================================================

# ---- Textos (Spanglish) -------------------------------------------------
GAME_TITLE     = "KAY´S SNAKE QUEST"
SUBTITLE       = "* NEON ARCADE EDITION *"
TEXT_INSERT    = "INSERT COIN"
TEXT_START     = "PRESS SPACE TO START"
TEXT_SCORE     = "SCORE"
TEXT_HISCORE   = "HI-SCORE"
TEXT_LEVEL     = "LEVEL"
TEXT_GAMEOVER  = "GAME OVER, BRO!"
TEXT_RESTART   = "PRESS SPACE - PLAY AGAIN"
TEXT_PAUSED    = "PAUSADO"
TEXT_RESUME    = "PRESS P TO RESUME"
TEXT_CONTROLS  = "FLECHAS / WASD - MOVER     P - PAUSA     ESC - SALIR"
TEXT_TAGLINE   = "READY?  ¡VAMOS!"
TEXT_COPYRIGHT = "(C) 202X   PIXEL DREAMS ARCADE"

# ---- Ventana / Window ---------------------------------------------------
INITIAL_WIDTH  = 960
INITIAL_HEIGHT = 720
WINDOW_TITLE   = "Kay´s Snake Quest"
TARGET_FPS     = 60

# ---- Tablero / Grid -----------------------------------------------------
GRID_COLS = 28   # cuántas columnas tiene el tablero
GRID_ROWS = 20   # cuántas filas

# ---- Velocidad / Speed --------------------------------------------------
# Más bajo = más rápido. Lower number = faster snake.
INITIAL_MOVE_DELAY_MS = 140   # delay inicial entre movimientos
MIN_MOVE_DELAY_MS     = 55    # límite máximo de velocidad
SPEED_UP_PER_LEVEL_MS = 8     # cuánto acelera cada nivel
FRUITS_PER_LEVEL      = 5     # frutas que necesitas para subir de nivel

# ---- Colores neón / Neon palette (R, G, B) -----------------------------
COLOR_BG           = (8,   6,  24)
COLOR_GRID_DIM     = (24, 18,  60)
COLOR_GRID_BRIGHT  = (40, 30, 100)
COLOR_BORDER       = (180, 90, 255)
COLOR_BORDER_GLOW  = (120, 60, 220)

COLOR_SNAKE_HEAD   = (170, 255, 200)
COLOR_SNAKE_BODY   = (40,  230, 140)
COLOR_SNAKE_GLOW   = (40,  255, 180)

COLOR_FRUIT        = (255, 60,  110)
COLOR_FRUIT_GLOW   = (255, 110, 160)
COLOR_FRUIT_LEAF   = (130, 255, 100)

COLOR_TEXT_PINK    = (255, 80,  200)
COLOR_TEXT_CYAN    = (90,  230, 255)
COLOR_TEXT_YELLOW  = (255, 230, 80)
COLOR_TEXT_WHITE   = (240, 240, 255)

# ---- Efecto CRT ---------------------------------------------------------
CRT_ENABLED        = True    # pon False para desactivar el CRT
SCANLINE_SPACING   = 3       # cada cuántos píxeles dibuja una línea
SCANLINE_ALPHA     = 55      # 0 (invisible) – 255 (opaco)
VIGNETTE_ENABLED   = True

# ---- Audio --------------------------------------------------------------
AUDIO_ENABLED      = True
MUSIC_VOLUME       = 0.4     # 0.0 – 1.0
SFX_VOLUME         = 0.5
# Música opcional. Si NO existe, el juego funciona normal (silencio).
MUSIC_FILE         = os.path.join("assets", "music", "theme.wav")


# ==========================================================================
#   IMPLEMENTACIÓN  —  Modifica con cuidado a partir de aquí
#   IMPLEMENTATION   —  Modify carefully from here onwards
# ==========================================================================

# Direcciones (dx, dy)
UP    = (0, -1)
DOWN  = (0,  1)
LEFT  = (-1, 0)
RIGHT = (1,  0)

# Estados de juego
STATE_MENU      = "menu"
STATE_PLAYING   = "playing"
STATE_PAUSED    = "paused"
STATE_GAMEOVER  = "gameover"


# --------------------------------------------------------------------------
#   GENERACIÓN DE SONIDO  /  SOUND GENERATION
#   Crea efectos de sonido por código (no necesita archivos .wav).
# --------------------------------------------------------------------------

def generate_tone(frequency=440, duration_ms=120, volume=0.3, wave="square"):
    """Genera un beep simple. Devuelve un pygame.mixer.Sound (o None si falla)."""
    try:
        sample_rate = 22050
        n_samples = max(1, int(sample_rate * duration_ms / 1000))
        buf = bytearray()
        for i in range(n_samples):
            t = i / sample_rate
            if wave == "square":
                s = 1.0 if (frequency * t) % 1.0 < 0.5 else -1.0
            elif wave == "triangle":
                phase = (frequency * t) % 1.0
                s = 4 * abs(phase - 0.5) - 1
            elif wave == "sawtooth":
                phase = (frequency * t) % 1.0
                s = 2 * phase - 1
            else:  # sine
                s = math.sin(2 * math.pi * frequency * t)
            # Envelope: ataque corto + decay suave
            attack = min(1.0, i / max(1, sample_rate * 0.005))
            decay = max(0.0, 1.0 - i / n_samples) ** 1.5
            sample = int(32767 * volume * s * attack * decay)
            sample = max(-32767, min(32767, sample))
            data = sample.to_bytes(2, "little", signed=True)
            # Stereo: escribimos a los dos canales
            buf += data + data
        return pygame.mixer.Sound(buffer=bytes(buf))
    except Exception as exc:
        print(f"[sound] tone gen failed: {exc}")
        return None


def generate_arpeggio(frequencies, note_ms=80, volume=0.3, wave="square"):
    """Encadena varias notas en un solo Sound (efecto melódico)."""
    try:
        sample_rate = 22050
        buf = bytearray()
        for f in frequencies:
            n = max(1, int(sample_rate * note_ms / 1000))
            for i in range(n):
                t = i / sample_rate
                if wave == "square":
                    s = 1.0 if (f * t) % 1.0 < 0.5 else -1.0
                elif wave == "triangle":
                    phase = (f * t) % 1.0
                    s = 4 * abs(phase - 0.5) - 1
                else:
                    s = math.sin(2 * math.pi * f * t)
                attack = min(1.0, i / max(1, sample_rate * 0.005))
                decay = max(0.0, 1.0 - i / n) ** 1.3
                sample = int(32767 * volume * s * attack * decay)
                sample = max(-32767, min(32767, sample))
                data = sample.to_bytes(2, "little", signed=True)
                buf += data + data
        return pygame.mixer.Sound(buffer=bytes(buf))
    except Exception as exc:
        print(f"[sound] arp gen failed: {exc}")
        return None


# --------------------------------------------------------------------------
#   CLASE PRINCIPAL DEL JUEGO  /  MAIN GAME CLASS
# --------------------------------------------------------------------------

class Game:
    def __init__(self):
        self.screen = pygame.display.set_mode(
            (INITIAL_WIDTH, INITIAL_HEIGHT),
            pygame.RESIZABLE,
        )
        pygame.display.set_caption(WINDOW_TITLE)
        self.width = INITIAL_WIDTH
        self.height = INITIAL_HEIGHT
        self.clock = pygame.time.Clock()

        self._init_fonts()

        self.sounds = {}
        self._init_sounds()

        self.crt_overlay = None
        self.vignette = None
        self._rebuild_overlays()

        # Estado de juego
        self.state = STATE_MENU
        self.high_score = 0
        self.reset()

        # Animaciones / tiempos
        self.time_ms = 0
        self.blink_timer = 0

    # ---------- Setup ----------

    def _init_fonts(self):
        # Usamos la fuente por defecto de pygame (funciona también en pygbag)
        self.font_huge  = pygame.font.Font(None, 96)
        self.font_big   = pygame.font.Font(None, 56)
        self.font_mid   = pygame.font.Font(None, 36)
        self.font_small = pygame.font.Font(None, 24)
        self.font_tiny  = pygame.font.Font(None, 18)

    def _init_sounds(self):
        if not AUDIO_ENABLED:
            return
        try:
            self.sounds["eat"]      = generate_tone(880, 90, 0.35, "square")
            self.sounds["levelup"]  = generate_arpeggio([523, 659, 784, 1047], 70, 0.35, "square")
            self.sounds["gameover"] = generate_arpeggio([392, 330, 262, 196], 150, 0.40, "triangle")
            self.sounds["start"]    = generate_arpeggio([523, 784, 1047], 80, 0.35, "square")
            self.sounds["turn"]     = generate_tone(1100, 28, 0.12, "square")
            self.sounds["pause"]    = generate_tone(440, 80, 0.25, "triangle")

            for snd in self.sounds.values():
                if snd is not None:
                    snd.set_volume(SFX_VOLUME)

            # Música de fondo (opcional)
            if os.path.exists(MUSIC_FILE):
                try:
                    pygame.mixer.music.load(MUSIC_FILE)
                    pygame.mixer.music.set_volume(MUSIC_VOLUME)
                    pygame.mixer.music.play(-1)
                    print(f"[music] Reproduciendo {MUSIC_FILE}")
                except Exception as exc:
                    print(f"[music] No pude reproducir {MUSIC_FILE}: {exc}")
            else:
                print(f"[music] No hay música en {MUSIC_FILE} — corriendo sin música (OK).")
        except Exception as exc:
            print(f"[audio] init failed: {exc}")

    def play(self, name):
        snd = self.sounds.get(name)
        if snd is not None:
            try:
                snd.play()
            except Exception:
                pass

    def _rebuild_overlays(self):
        """Re-crea los overlays de CRT cuando cambia el tamaño de ventana."""
        if CRT_ENABLED:
            self.crt_overlay = pygame.Surface((self.width, self.height), pygame.SRCALPHA)
            for y in range(0, self.height, SCANLINE_SPACING):
                pygame.draw.line(
                    self.crt_overlay,
                    (0, 0, 0, SCANLINE_ALPHA),
                    (0, y), (self.width, y),
                )
        else:
            self.crt_overlay = None

        if VIGNETTE_ENABLED:
            self.vignette = pygame.Surface((self.width, self.height), pygame.SRCALPHA)
            steps = 36
            for i in range(steps):
                a = int(160 * (i / steps) ** 2)
                pad_x = int((self.width / 2) * (1 - i / steps))
                pad_y = int((self.height / 2) * (1 - i / steps))
                w = max(1, self.width - pad_x * 2)
                h = max(1, self.height - pad_y * 2)
                pygame.draw.rect(
                    self.vignette,
                    (0, 0, 0, a),
                    (pad_x, pad_y, w, h),
                    width=3,
                )
        else:
            self.vignette = None

    def on_resize(self, w, h):
        self.width = max(420, w)
        self.height = max(320, h)
        self.screen = pygame.display.set_mode((self.width, self.height), pygame.RESIZABLE)
        self._rebuild_overlays()

    # ---------- Layout ----------

    @property
    def play_rect(self):
        """Devuelve (rect, cell_size) del tablero — siempre cuadrado por celda."""
        margin_x = 40
        top_hud = 90
        bottom = 50
        avail_w = self.width - margin_x * 2
        avail_h = self.height - top_hud - bottom
        cs = max(6, min(avail_w // GRID_COLS, avail_h // GRID_ROWS))
        w = cs * GRID_COLS
        h = cs * GRID_ROWS
        x = (self.width - w) // 2
        y = top_hud + (avail_h - h) // 2
        return pygame.Rect(x, y, w, h), cs

    # ---------- Lógica de juego / Game logic ----------

    def reset(self):
        cx, cy = GRID_COLS // 2, GRID_ROWS // 2
        # Snake: lista de celdas. El último elemento es la CABEZA.
        self.snake = [(cx - 2, cy), (cx - 1, cy), (cx, cy)]
        self.direction = RIGHT
        self.next_direction = RIGHT
        self.score = 0
        self.level = 1
        self.move_delay = INITIAL_MOVE_DELAY_MS
        self.move_timer = 0
        self.fruit = self._random_empty_cell()
        self.fruit_pulse = 0.0

    def _random_empty_cell(self):
        occupied = set(self.snake)
        empties = [(x, y) for x in range(GRID_COLS)
                          for y in range(GRID_ROWS)
                          if (x, y) not in occupied]
        if not empties:
            return None
        return random.choice(empties)

    def try_set_direction(self, new_dir):
        # Prohíbe el 180° instantáneo (te matarías solo)
        if new_dir[0] == -self.direction[0] and new_dir[1] == -self.direction[1]:
            return
        if new_dir != self.next_direction:
            self.play("turn")
        self.next_direction = new_dir

    def step_snake(self):
        self.direction = self.next_direction
        head_x, head_y = self.snake[-1]
        nx, ny = head_x + self.direction[0], head_y + self.direction[1]

        # Colisión con la pared
        if nx < 0 or nx >= GRID_COLS or ny < 0 or ny >= GRID_ROWS:
            self.game_over()
            return

        new_head = (nx, ny)
        will_eat = (self.fruit is not None and new_head == self.fruit)

        # Colisión con el cuerpo (la cola se moverá si NO come, así que no cuenta)
        body_to_check = self.snake if will_eat else self.snake[1:]
        if new_head in body_to_check:
            self.game_over()
            return

        self.snake.append(new_head)

        if will_eat:
            self.score += 10
            if self.score > self.high_score:
                self.high_score = self.score
            self.play("eat")

            new_level = 1 + self.score // (10 * FRUITS_PER_LEVEL)
            if new_level > self.level:
                self.level = new_level
                self.move_delay = max(
                    MIN_MOVE_DELAY_MS,
                    INITIAL_MOVE_DELAY_MS - SPEED_UP_PER_LEVEL_MS * (self.level - 1),
                )
                self.play("levelup")

            self.fruit = self._random_empty_cell()
            if self.fruit is None:
                # ¡Llenaste el tablero! Bonus + game over.
                self.score += 500
                self.high_score = max(self.high_score, self.score)
                self.game_over()
        else:
            self.snake.pop(0)  # mover la cola

    def game_over(self):
        self.state = STATE_GAMEOVER
        self.play("gameover")

    # ---------- Update ----------

    def update(self, dt):
        self.time_ms += dt
        self.blink_timer = (self.blink_timer + dt) % 1000
        self.fruit_pulse = (self.fruit_pulse + dt * 0.005) % (math.pi * 2)

        if self.state == STATE_PLAYING:
            self.move_timer += dt
            if self.move_timer >= self.move_delay:
                self.move_timer -= self.move_delay
                self.step_snake()

    # ---------- Draw ----------

    def draw(self):
        self.screen.fill(COLOR_BG)
        rect, cs = self.play_rect
        self.draw_grid(rect, cs)

        if self.state == STATE_MENU:
            self.draw_menu()
        else:
            self.draw_fruit(rect, cs)
            self.draw_snake(rect, cs)
            self.draw_hud(rect)
            if self.state == STATE_PAUSED:
                self.draw_pause_overlay()
            elif self.state == STATE_GAMEOVER:
                self.draw_gameover_overlay()

        # Overlays CRT al final (encima de todo)
        if self.crt_overlay:
            self.screen.blit(self.crt_overlay, (0, 0))
        if self.vignette:
            self.screen.blit(self.vignette, (0, 0))

        pygame.display.flip()

    # ---- Drawing helpers ----

    def draw_grid(self, rect, cs):
        # Borde con "glow"
        pygame.draw.rect(self.screen, COLOR_BORDER_GLOW, rect.inflate(12, 12), border_radius=6)
        pygame.draw.rect(self.screen, COLOR_BG,          rect.inflate(8, 8),   border_radius=4)
        pygame.draw.rect(self.screen, COLOR_BORDER,      rect, width=2)

        # Líneas finas
        for c in range(GRID_COLS + 1):
            x = rect.left + c * cs
            pygame.draw.line(self.screen, COLOR_GRID_DIM, (x, rect.top), (x, rect.bottom))
        for r in range(GRID_ROWS + 1):
            y = rect.top + r * cs
            pygame.draw.line(self.screen, COLOR_GRID_DIM, (rect.left, y), (rect.right, y))

        # Líneas más brillantes cada 4 celdas (estética arcade)
        for c in range(0, GRID_COLS + 1, 4):
            x = rect.left + c * cs
            pygame.draw.line(self.screen, COLOR_GRID_BRIGHT, (x, rect.top), (x, rect.bottom))
        for r in range(0, GRID_ROWS + 1, 4):
            y = rect.top + r * cs
            pygame.draw.line(self.screen, COLOR_GRID_BRIGHT, (rect.left, y), (rect.right, y))

    def draw_snake(self, rect, cs):
        # Glow / halo (rectángulos expansivos sin relleno)
        for gx, gy in self.snake:
            px = rect.left + gx * cs
            py = rect.top  + gy * cs
            pygame.draw.rect(self.screen, COLOR_SNAKE_GLOW,
                             (px - 2, py - 2, cs + 4, cs + 4),
                             width=1, border_radius=4)

        # Cuerpo
        for gx, gy in self.snake[:-1]:
            px = rect.left + gx * cs + 2
            py = rect.top  + gy * cs + 2
            pygame.draw.rect(self.screen, COLOR_SNAKE_BODY,
                             (px, py, cs - 4, cs - 4), border_radius=3)
            # Brillo interior
            if cs >= 14:
                pygame.draw.rect(self.screen, COLOR_SNAKE_HEAD,
                                 (px + 2, py + 2, cs - 8, cs - 8),
                                 width=1, border_radius=2)

        # Cabeza
        hx, hy = self.snake[-1]
        px = rect.left + hx * cs + 1
        py = rect.top  + hy * cs + 1
        pygame.draw.rect(self.screen, COLOR_SNAKE_HEAD,
                         (px, py, cs - 2, cs - 2), border_radius=4)

        # Ojos
        eye_offset = max(2, cs // 5)
        eye_size = max(2, cs // 8)
        dx, dy = self.direction
        if dx == 1:    # mira a la derecha
            e1 = (px + cs - eye_offset - 3, py + eye_offset)
            e2 = (px + cs - eye_offset - 3, py + cs - eye_offset - 4)
        elif dx == -1: # izquierda
            e1 = (px + eye_offset, py + eye_offset)
            e2 = (px + eye_offset, py + cs - eye_offset - 4)
        elif dy == -1: # arriba
            e1 = (px + eye_offset, py + eye_offset)
            e2 = (px + cs - eye_offset - 4, py + eye_offset)
        else:          # abajo
            e1 = (px + eye_offset, py + cs - eye_offset - 4)
            e2 = (px + cs - eye_offset - 4, py + cs - eye_offset - 4)
        pygame.draw.rect(self.screen, COLOR_BG, (*e1, eye_size, eye_size))
        pygame.draw.rect(self.screen, COLOR_BG, (*e2, eye_size, eye_size))

    def draw_fruit(self, rect, cs):
        if not self.fruit:
            return
        gx, gy = self.fruit
        px = rect.left + gx * cs + cs // 2
        py = rect.top  + gy * cs + cs // 2

        pulse = (math.sin(self.fruit_pulse) + 1) / 2  # 0..1
        radius = max(3, int(cs * 0.38 + pulse * 1.5))
        glow_r = max(radius + 2, int(cs * 0.65 + pulse * 3))

        # Halo (concentric semi-transparent circles)
        glow_surf = pygame.Surface((glow_r * 2 + 4, glow_r * 2 + 4), pygame.SRCALPHA)
        for k in range(4, 0, -1):
            alpha = int(45 * k / 4)
            r = int(glow_r * k / 4)
            pygame.draw.circle(glow_surf, (*COLOR_FRUIT_GLOW, alpha),
                               (glow_r + 2, glow_r + 2), r)
        self.screen.blit(glow_surf, (px - glow_r - 2, py - glow_r - 2))

        # Cuerpo de la manzana
        pygame.draw.circle(self.screen, COLOR_FRUIT, (px, py), radius)
        # Brillo
        pygame.draw.circle(self.screen, COLOR_FRUIT_GLOW,
                           (px - radius // 3, py - radius // 3),
                           max(2, radius // 3))
        # Hoja
        leaf_w = max(3, cs // 5)
        leaf_h = max(2, cs // 7)
        pygame.draw.ellipse(self.screen, COLOR_FRUIT_LEAF,
                            (px + 1, py - radius - leaf_h, leaf_w, leaf_h))

    def draw_hud(self, rect):
        y = 22
        # SCORE (izquierda)
        score_str = f"{TEXT_SCORE}  {self.score:06d}"
        self.draw_neon_text(self.font_mid, score_str,
                            (rect.left + 4, y),
                            COLOR_TEXT_CYAN, COLOR_TEXT_CYAN, center=False)

        # HI-SCORE (centro)
        hi_str = f"{TEXT_HISCORE}  {self.high_score:06d}"
        self.draw_neon_text(self.font_mid, hi_str,
                            (self.width // 2, y + 12),
                            COLOR_TEXT_YELLOW, COLOR_TEXT_YELLOW, center=True)

        # LEVEL (derecha)
        lvl_str = f"{TEXT_LEVEL} {self.level:02d}"
        lvl_surf = self.font_mid.render(lvl_str, True, COLOR_TEXT_PINK)
        self.draw_neon_text(self.font_mid, lvl_str,
                            (rect.right - lvl_surf.get_width() - 4, y),
                            COLOR_TEXT_PINK, COLOR_TEXT_PINK, center=False)

        # Footer de controles
        self.draw_neon_text(self.font_small, TEXT_CONTROLS,
                            (self.width // 2, self.height - 25),
                            COLOR_TEXT_WHITE, COLOR_TEXT_PINK, center=True)

    def draw_menu(self):
        # Título con leve "flotación"
        t = self.time_ms / 600
        title_y = max(120, self.height // 4) + int(math.sin(t) * 6)

        self.draw_neon_text(self.font_huge, GAME_TITLE,
                            (self.width // 2, title_y),
                            COLOR_TEXT_PINK, COLOR_TEXT_PINK, center=True)
        self.draw_neon_text(self.font_mid, SUBTITLE,
                            (self.width // 2, title_y + 65),
                            COLOR_TEXT_CYAN, COLOR_TEXT_CYAN, center=True)
        self.draw_neon_text(self.font_mid, f"{TEXT_HISCORE}  {self.high_score:06d}",
                            (self.width // 2, title_y + 120),
                            COLOR_TEXT_YELLOW, COLOR_TEXT_YELLOW, center=True)

        # Culebrita decorativa que se ondula
        seg_count = 14
        seg_size = max(12, self.width // 60)
        for i in range(seg_count):
            phase = self.time_ms / 200 + i * 0.4
            x = self.width // 2 + math.cos(phase) * (seg_count * seg_size * 0.45)
            y = title_y + 200 + math.sin(phase) * 28
            pygame.draw.rect(self.screen, COLOR_SNAKE_GLOW,
                             (x - seg_size // 2 - 2, y - seg_size // 2 - 2,
                              seg_size + 4, seg_size + 4),
                             width=1, border_radius=3)
            pygame.draw.rect(self.screen, COLOR_SNAKE_BODY,
                             (x - seg_size // 2, y - seg_size // 2, seg_size, seg_size),
                             border_radius=3)

        # "INSERT COIN" parpadeante
        blink = (self.blink_timer // 500) % 2 == 0
        if blink:
            self.draw_neon_text(self.font_big, TEXT_INSERT,
                                (self.width // 2, self.height - 220),
                                COLOR_TEXT_YELLOW, COLOR_TEXT_PINK, center=True)

        self.draw_neon_text(self.font_mid, TEXT_START,
                            (self.width // 2, self.height - 155),
                            COLOR_TEXT_CYAN, COLOR_TEXT_CYAN, center=True)
        self.draw_neon_text(self.font_small,
                            "FLECHAS / WASD - MOVER     P - PAUSA",
                            (self.width // 2, self.height - 105),
                            COLOR_TEXT_WHITE, COLOR_TEXT_WHITE, center=True)
        self.draw_neon_text(self.font_small, TEXT_TAGLINE,
                            (self.width // 2, self.height - 70),
                            COLOR_TEXT_PINK, COLOR_TEXT_PINK, center=True)
        self.draw_neon_text(self.font_tiny, TEXT_COPYRIGHT,
                            (self.width // 2, self.height - 30),
                            COLOR_TEXT_WHITE, COLOR_TEXT_WHITE, center=True)

    def draw_pause_overlay(self):
        overlay = pygame.Surface((self.width, self.height), pygame.SRCALPHA)
        overlay.fill((0, 0, 0, 140))
        self.screen.blit(overlay, (0, 0))
        self.draw_neon_text(self.font_huge, TEXT_PAUSED,
                            (self.width // 2, self.height // 2 - 30),
                            COLOR_TEXT_YELLOW, COLOR_TEXT_YELLOW, center=True)
        self.draw_neon_text(self.font_mid, TEXT_RESUME,
                            (self.width // 2, self.height // 2 + 50),
                            COLOR_TEXT_CYAN, COLOR_TEXT_CYAN, center=True)

    def draw_gameover_overlay(self):
        overlay = pygame.Surface((self.width, self.height), pygame.SRCALPHA)
        overlay.fill((0, 0, 0, 160))
        self.screen.blit(overlay, (0, 0))
        self.draw_neon_text(self.font_huge, TEXT_GAMEOVER,
                            (self.width // 2, self.height // 2 - 60),
                            COLOR_TEXT_PINK, COLOR_TEXT_PINK, center=True)
        self.draw_neon_text(self.font_big, f"{TEXT_SCORE}  {self.score:06d}",
                            (self.width // 2, self.height // 2 + 15),
                            COLOR_TEXT_WHITE, COLOR_TEXT_CYAN, center=True)
        blink = (self.blink_timer // 500) % 2 == 0
        if blink:
            self.draw_neon_text(self.font_mid, TEXT_RESTART,
                                (self.width // 2, self.height // 2 + 90),
                                COLOR_TEXT_YELLOW, COLOR_TEXT_YELLOW, center=True)

    def draw_neon_text(self, font, text, pos, color, glow_color, center=True):
        """Dibuja texto con un halo neón detrás (multi-pase con alpha)."""
        glow = font.render(text, True, glow_color)
        glow.set_alpha(70)
        offsets = [(-2, 0), (2, 0), (0, -2), (0, 2),
                   (-1, -1), (1, 1), (-1, 1), (1, -1)]
        for ox, oy in offsets:
            r = glow.get_rect()
            if center:
                r.center = (pos[0] + ox, pos[1] + oy)
            else:
                r.topleft = (pos[0] + ox, pos[1] + oy)
            self.screen.blit(glow, r)
        base = font.render(text, True, color)
        r = base.get_rect()
        if center:
            r.center = pos
        else:
            r.topleft = pos
        self.screen.blit(base, r)


# --------------------------------------------------------------------------
#   ASYNC MAIN LOOP  (compatible con pygbag)
# --------------------------------------------------------------------------

async def main():
    # Hint al mixer ANTES de pygame.init (mejor sonido, menos latencia)
    try:
        pygame.mixer.pre_init(frequency=22050, size=-16, channels=2, buffer=512)
    except Exception:
        pass

    pygame.init()

    if AUDIO_ENABLED and not pygame.mixer.get_init():
        try:
            pygame.mixer.init(frequency=22050, size=-16, channels=2, buffer=512)
        except Exception as exc:
            print(f"[audio] mixer init failed: {exc}")

    game = Game()
    game.play("start")
    running = True

    while running:
        dt = game.clock.tick(TARGET_FPS)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

            elif event.type == pygame.VIDEORESIZE:
                game.on_resize(event.w, event.h)

            elif event.type == pygame.KEYDOWN:
                key = event.key

                if key == pygame.K_ESCAPE:
                    if game.state == STATE_MENU:
                        running = False
                    else:
                        game.state = STATE_MENU
                        game.reset()

                elif key == pygame.K_SPACE:
                    if game.state == STATE_MENU:
                        game.reset()
                        game.state = STATE_PLAYING
                        game.play("start")
                    elif game.state == STATE_GAMEOVER:
                        game.reset()
                        game.state = STATE_PLAYING
                        game.play("start")

                elif key == pygame.K_p:
                    if game.state == STATE_PLAYING:
                        game.state = STATE_PAUSED
                        game.play("pause")
                    elif game.state == STATE_PAUSED:
                        game.state = STATE_PLAYING
                        game.play("pause")

                # Controles de movimiento solo cuando estás jugando
                if game.state == STATE_PLAYING:
                    if key in (pygame.K_UP, pygame.K_w):
                        game.try_set_direction(UP)
                    elif key in (pygame.K_DOWN, pygame.K_s):
                        game.try_set_direction(DOWN)
                    elif key in (pygame.K_LEFT, pygame.K_a):
                        game.try_set_direction(LEFT)
                    elif key in (pygame.K_RIGHT, pygame.K_d):
                        game.try_set_direction(RIGHT)

        game.update(dt)
        game.draw()

        # ¡IMPORTANTE para pygbag! Cede control al event loop del navegador.
        await asyncio.sleep(0)

    pygame.quit()


if __name__ == "__main__":
    asyncio.run(main())